name: twity_bird_badminton

description: "A project to keep track of badminton players"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: ^0.19.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_fonts: ^6.1.0
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/